### PR TITLE
Synchronize Challonge API calls and respect caching

### PR DESCRIPTION
**Pull request by kevinlul**
## Description

Through empirical testing, Challonge handles concurrency tremendously poorly. Multiple requests on the same tournament when one has yet to respond could fatally break the tournament outright. This synchronizes all requests made by a WebsiteWrapperChallonge instance, so we only make one request at a time, though we probably only need to synchronize requests on the same tournament. This is achieved with [`async-mutex`](https://github.com/DirtyHairy/async-mutex).

Furthermore, Challonge seems to support [weak ETags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag), so we switch to npm's compatible [`make-fetch-happen`](https://github.com/npm/make-fetch-happen), a client aware of HTTP cache semantics, for WebsiteWrapperChallonge. This should improve performance for frequently called APIs like getting the match list, and we don't have to implement cache awareness on top of node-fetch ourselves. `make-fetch-happen` also happens to support retries, so we'll try one that should happen after one second, according to documentation.

A global error handler now provides users with some feedback when Challonge borks.

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).
- [x] I have updated any relevant [user guides](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/guides).
- [x] I have updated any relevant [documentation](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/docs).
- [x] I have updated the [changelog](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/changelog.md), or this change is not user-facing.

### CODE REVIEW

**Comment by kevinlul** [comment]
Note: should do a tournament test run together.

**Review by AlphaKretin — COMMENTED** [review]
A lot of warnings here I'd like to see cleaned up, otherwise code looks good pending practical test

**Comment by kevinlul** [comment]
Did you mean the linter warnings elsewhere?

**Comment by AlphaKretin** [comment]
I thought I saw more in this PR than in others but I could be wrong

**Comment by kevinlul** [comment]
This is a pure internals change. Should we add anything to the changelog?

**Comment by AlphaKretin** [comment]
We could add a note about an expected increase in stability, since the point of the changes is to fix a pretty shoddy end-user experience

**Review by AlphaKretin — APPROVED** [review]

**Pull request merged**
