### PR TITLE
Fix issues with /start command

### PR DESCRIPTION
**Pull request by AlphaKretin**
## Description

Drop unapproved players and commit the tournament status

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).
- [ ] I have updated any relevant [user guides](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/guides).
- [ ] I have updated any relevant [documentation](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/docs).
- [ ] I have updated the [changelog](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/changelog.md), or this change is not user-facing.

### CODE REVIEW

**Comment by AlphaKretin** [comment]
Note: The relevant card in the project also says to delete the register message, but the code already done this, so if that's not happening in practice we need to debug

**Review by kevinlul — COMMENTED** [review]
Is this fully comparable to mc!start?

**Comment by AlphaKretin** [comment]
`mc!start` workflow
- Checks that there are at least two participants. Without round management features this isn't directly analogous. Though we could check that the `/queue` is empty?
- Drops pending participants (Done)
- Deletes register messages, effectively closing submissions (We close later, but set to IPR sooner)
- Sets up players and the Challonge bracket (irrelevant)
- Set tournament to IPR (done)
- Sends command guides to players and hosts (former irrelevant, latter not in scope?)
- Manage round-one byes (irrelevant)

So I think we have everything?

**Comment by kevinlul** [comment]
Okay, do remove the register message first before committing the database change.

**Review by kevinlul — APPROVED** [review]

**Pull request merged**
