### PR TITLE
Change member nickname on registration

### PR DESCRIPTION
**Pull request by AlphaKretin**
## Description

Specified feature.

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/.github/CONTRIBUTING.md).
- [ ] I have updated any relevant [user guides](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/guides).
- [ ] I have updated any relevant [documentation](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/docs).
- [ ] I have updated the [changelog](https://github.com/DawnbrandBots/emcee-tournament-bot/blob/master/changelog.md), or this change is not user-facing.

### CODE REVIEW

**Comment by kevinlul** [comment]
Maybe do this upon approval or do some naive check to make sure a friend code is not already somewhere in there. Otherwise this could get gnarly

**Comment by AlphaKretin** [comment]
Good call.

**Comment by AlphaKretin** [comment]
The "naive check" approach is simpler because we don't already have the member in the approval stage. Though, we could potentially fetch tournament guild and then guild member, instead of fetching the user.

**Review by kevinlul — APPROVED** [review]
Good. Add a backlog item to request Change Nickname permissions for this. Won't matter for where this is being used.

**Pull request merged**
